### ISSUE TITLE
Using mdlink within a table?

### ISSUE THREAD

**Issue by jasonplumb** [chuhlomin/render-template#11]
First of all, great github action!

For the example

```
mdlink – creates markdown link.
Example: {{ "https://github.com" | mdlink "GitHub" }} will be rendered as [GitHub](https://github.com).
```

I was wondering if there would be a way/future support to allow the above to work within a markdown table such as:

```
| Github Link                        | Twitter Link                      |
| ----------------------------------- | ------------------------------- |
| {{ "https://github.com" | mdlink "GitHub" }} | {{ "https://twitter.com" | mdlink "Twitter" }} |
```

**Comment by chuhlomin** [comment]
Hey, I'm glad you appreciate this GitHub Action.

This is already supported. Action uses Go templates, so it doesn't really matter where you use template functions like `mdlink`. You can use it in a markdown table, in a JSON file, in a YAML file, in a text file, etc.
Check out the example: [template](https://github.com/chuhlomin/render-template/compare/feat/md-table?expand=1#diff-57d561ae922dcc33e3504c37a71b1981e46e5ffd253753fc175b658de46233c4), [action run](https://github.com/chuhlomin/render-template/actions/runs/5419396842/jobs/9852451403)
