### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by a-cesari** [chuhlomin/render-template#13]
Dear @chuhlomin ,

again thanks for the amazing action. 
As for my project I need to run it on a arm64 runner, are you thinking to compile the docker image for arm64 platform too?
Of course I can clone the repository and do it on my own, but I wanted to first reach out to you since I think it could be helpful to other people to have everything on you repo. 
Willing to help on this if you want. 
Let me know what do you think.

Best,
Andrea

**Comment by chuhlomin** [comment]
Hi Andrea,

Added multi-achitecture Docker image support in 1.8
Supported architectures are `linux/amd64`, `linux/arm/v7`, `linux/arm64`.
Give it a try: `chuhlomin/render-template@v1.8`

Thanks,
Konstantin

**Comment by pavlospt** [comment]
It doesn't work properly in Arm64 architecture. The binary seems to be compiled for a different architecture, so it outputs the following error, indicating that:
```
exec /app: exec format error
```

**Comment by pavlospt** [comment]
@chuhlomin PR fixing this: https://github.com/chuhlomin/render-template/pull/17 Has been tested locally!
