### ISSUE TITLE
Support rolling tags

### ISSUE THREAD

**Issue by tooomm** [chuhlomin/render-template#14]
I would love to simply put
```
      - name: Render template
        uses: chuhlomin/render-template@v1
```

and be ensured to always run the latest (non breaking) fixes and features.

Breaking changes should then be moved to a v2.x release etc.

<br>

Did you ever consider that? @chuhlomin

**Comment by chuhlomin** [comment]
Hey @tooomm,

Good idea! I updated the `v1` tag, so now it works.
The exact version will be shown in the logs.

**Comment by tooomm** [comment]
I can confirm. Your update works smoothly! 👍 

Thanks for the quick fix.

You now also don't need to keep the readme up to date with the newest version. Maybe put a note?
But remember to move the main version tag now with new releases.

**Comment by chuhlomin** [comment]
Updated readme and added the step to GitHub Actions to automate tag update after manual approval. Thanks for the great suggestions!

**Comment by tooomm** [comment]
Cool, the automation steps for this in https://github.com/chuhlomin/render-template/commit/0ca00227d0eff8f1e5bfcf3632f61bfd5f9bb5b1 look good.
I was not aware of the environments in GitHub Actions, interesting!
