### ISSUE TITLE
Conversion of special characters in template data

### ISSUE THREAD

**Issue by rkleinman-hpe** [chuhlomin/render-template#2]
I have a template that prints out the version of my Helm chart

```
    version: "{{ .chartVersion }}"
```

where the version string may sometimes contain characters like `+`. Example: `1.5.0-PullRequest0031.33.20220104212638.d0533b9`

When rendered the output looks like this: 
```
    version: "1.5.0-PullRequest0031.33&#43;20220104212638.d0533b9"
```

Is there a way to get special characters to not be encoded?

**Comment by rkleinman-hpe** [comment]
Possibly due to the use of "html/template" instead of "text/template"? 

https://github.com/chuhlomin/render-template/blob/main/main.go#L7

See https://stackoverflow.com/a/48527166/576333

**Comment by chuhlomin** [comment]
Thanks for brining this up! There is no reason to use `html/template` package.
Switched to `text/template` in [v1.4 release](https://github.com/chuhlomin/render-template/releases/tag/v1.4). Please, give it a try.
