### ISSUE TITLE
Unknown input result_path

### ISSUE THREAD

**Issue by joenexus** [chuhlomin/render-template#4]
Using input result_path triggers the error below:

```
Unexpected input(s) 'result_path', valid inputs are ['entryPoint', 'args', 'template', 'vars']
```

**Comment by chuhlomin** [comment]
Hey, you are likely using version 1.2. I added `result_path` only in 1.3. See [Releases](https://github.com/chuhlomin/render-template/releases).
Here is an example: https://github.com/chuhlomin/actions/blob/main/deploy-gke/action.yml#L44-L49
