### ISSUE TITLE
Variables from filepath

### ISSUE THREAD

**Issue by parmouraly** [chuhlomin/render-template#5]
Hey 👋 

Thanks for this great library.
It would be very useful for me if the variables came from a file instead (so I can have different files per environment).

I don't suppose this would be difficult. Any chance you'd consider implementing this?
I might have a go if I get some time but I imagine it'll take you less time to build this in as you're already setup with your devenv.

In any case many thanks!

**Comment by chuhlomin** [comment]
Hey, I like that idea.
Just published a [v1.5 release](https://github.com/chuhlomin/render-template/releases/tag/v1.5) – added `vars_path` input.
Give it a try

**Comment by parmouraly** [comment]
Thanks @chuhlomin that was quick!
In the meantime I hadn't realised that the template one uses has to be a go template.
I had thought it would be possible to use a json file for example.
So that's of limited use to me after all.

**Comment by chuhlomin** [comment]
Hey, nothing stops you from using JSON file as template.
Here is an example:
https://github.com/chuhlomin/ip/pull/2/files
https://github.com/chuhlomin/ip/runs/6656398330
