### ISSUE TITLE
template file not found

### ISSUE THREAD

**Issue by lucasff** [chuhlomin/render-template#6]
Hello, I would appreciate a lot some support.
With the following

```yaml
with:
  template: .github/comment-template-preview-env.md
```

failed to render template: template file not found (".github/comment-template-preview-env.md")

I get the error the file is not found. I'm assuming this is due to the file not being available in your container? Can you help me figure out how GH Actions is supposed to work, or maybe improve the documentation with some necessary code that I'm missing?

Thank you in advance

**Comment by chuhlomin** [comment]
Hi, do you have this step in your workflow?

```yaml
      - name: Checkout
        uses: actions/checkout@v2
```

For some reason GitHub Actions does not checkout repository by default.
Here is a demonstration: https://github.com/chuhlomin/ip/runs/6619964775 for workflow https://github.com/chuhlomin/ip/blob/workflow-test/.github/workflows/pull_request.yml

**Comment by a-cesari** [comment]
Hi @chuhlomin ,
I have the same problem. I'm using last version (v1.7).
I created the following template file `mail-not-found-template.md` at this folder inside my repository: `templates\mail-not-found-template.md`

```
Dear {{ .user }},

we couldn't find the mail address in you Github profile.
Please follow these steps to set it, then **follow again the same procedure**.

- Click on your profile picture/avatar in the top right of the screen
- Click on `Your Profile`
- On the left, click on `Edit Profile`
- In the left side, from the dropdown menu close to the mail icon :email:, choose your email address 
```

However I get the `file not found error` when rendering the template. 
I have the checkout step in my workflow, as you can see that the file is there if I list the `GITHUB_WORKSPACE` folder.


![Capture](https://github.com/chuhlomin/render-template/assets/6312038/795f3f33-a275-4361-a5d7-49ac770d07b7)

And this is the error in the rendering steps:

![Capture2](https://github.com/chuhlomin/render-template/assets/6312038/9587713e-b7b4-4991-8610-381e9a265c62)

Thanks a lor for your kind help.
Andrea

**Comment by chuhlomin** [comment]
Hey @a-cesari, this error is a bit different: `failed to open result file "": open : no such file or directory`.
It is related to how action sets output values. GitHub Actions should automatically pass the `GITHUB_OUTPUT` environment variable with a path to the file where the action can write output values. Unfortunately, it looks like it didn't in your case.
Are you running your actions on a self-hosted runner? If so, perhaps, if should be updated.

**Comment by a-cesari** [comment]
Yes, I'm on self hosted runners, however I installed it last week so it should be quite recent versions. 
I'm running `actions-runner-linux-x64-2.296.3.tar.gz`, which is quite recent but I will anyway try to update to the latest `v2.304.0` and give you a feedback. 
Indeed I also tried to setup the `result_path` but without success.

**Comment by a-cesari** [comment]
I confirm that the action is working properly with the latest github runner
(v2.304.0)

Il giorno gio 18 mag 2023 alle 18:14 Konstantin Chukhlomin <
***@***.***> ha scritto:
