### ISSUE TITLE
Formatting options for placeholders?

### ISSUE THREAD

**Issue by Andre601** [chuhlomin/render-template#8]
This may be a bit out of scope for this action, but I feel like it could be a neat addition to have additional formatting options available for the different vars added in a template file.

To give an example: I'm currently implementing this action in a workflow to post a comment which contains links to the build artifact to a PR.
One of the vars I would include within this workflow is an expire date for when the artifacts will become unavailable (I use GitHub Action's artifact system).

My full template is like this:
```markdown
<!-- pr-build comment -->

![badge](<!-- url omitted. Too long -->)

The build of this PR has completed successfully!  
Below can you find a link for a direct download of the artifacts for this PR (GitHub Account required).

File expires: `{{ .expire-date }}`

| Name     | Link            |
|----------|-----------------|
| Commit   | {{ .commit }}   |
| Logs     | {{ .logs }}     |
| Download | {{ .download }} |
```
This, if I setup the action properly, would result in a Date such as `2023-08-06T15:08:28Z` which while readable, isn't that pretty to look at.

So I would like to propose some options to render certain vars in a different way.

Right now can I think of the following options:

- `number`
  - Format: `{{ .<var> | number [format] }}`
  - Renders the provided String as a number with proper separators (commas and dots)
  - Default format would be `#,###,###.##` but could be overriden by providing your own `[format]`.
- `link`
  - Format: `{{ .<var> | link }}`
  - Renders the provided String as an embeded link, with the name being the var. I.e. `{{ .download | link }}` becomes `[download](https://example.com)`
- `date`
  - Format: `{{ .<var> | date [format] }}`
  - Renders the provided String as a Date.
  - Default format would be `dd/mm/yyyy hh:MM:ss z` but could be overriden by providing your own `[format]`

I hope this is doable, but would also understand if this entire thing would be out of scope for this action itself.

**Comment by chuhlomin** [comment]
Hey @Andre601,
I like that idea and been thinking about something like this for some time.

Check out this PR: https://github.com/chuhlomin/render-template/pull/9
I've added a few functions like `date`, `mdlink` and `numbers`.
Usage example:
```
{{ "2023-08-06T15:08:28Z" | date "2006-01-02" }}
{{ "https://github.com" | mdlink "download" }}
{{ "1000" | number }}
```
`date` accepts Go time layout, see examples here: https://pkg.go.dev/time#pkg-constants

Let me know what you think.

**Comment by Andre601** [comment]
I'm a bit confused regarding the time formats supported... Do I need to provide an actual arbitrary date (i.e. `01. Jan 1970 00:00:00`) or does it allow placeholder text like in my example the `dd. mmm yyyy hh:MM:ss`?

It's a bit confusing to me.

**Comment by chuhlomin** [comment]
Time format layouts in Go defined like "how do you want the date look like as if it was January 2, 15:04:05, 2006"
So if you want time format like `dd mmm yyyy hh:MM:ss` then in template you'd need to write something like this:
```
{{ .expire-date | date "02 Jan 2006 15:04:05" }}
```

**Comment by Andre601** [comment]
Okay. Is the date anything I want, or does it have to be this specific date and time? Just want to make sure.

**Comment by chuhlomin** [comment]
It has to be a specific date and time, corresponding to 1136239445 Unix timestamp.

**Comment by Andre601** [comment]
Unrelated to this but that timestamp actually has 23:04:05 as the GMT time (Which if my brain works right should be UTC)... So either the timestamp is wrong or Go has a bad example xD

**Comment by Andre601** [comment]
Is something wrong with the way I set up the template path here?
```yaml
    steps:
      - name: Render Markdown Template
        id: render
        uses: chuhlomin/render-template@v1f41b8ed07508ba92b8501e7105c8c9632c73fc9
        with:
          template: .github/assets/pr-comments/failed.md
          vars: |
            commit: ${{ github.event.pull_request.head.sha }}
            logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
```
The files do exist in that specific path... Do I have to put a `./` before `.github` to tell the action to actually use this path?

**Comment by Andre601** [comment]
Okay... it doesn't work with a `./` prefix either...

Really don't know why it won't work. The file does exist:
![grafik](https://github.com/chuhlomin/render-template/assets/11576465/be81eb98-f643-4932-bf47-3ffc9447644c)

**Comment by Andre601** [comment]
Okay. Found it. It's the same issue as #6 

Tho, now I get `Error: failed to render template: template: ./.github/assets/pr-comments/success.md:7: bad character U+002D '-'` which I assume means that I can't have hyphons in the var names? Why is that?

**Comment by Andre601** [comment]
Okay.

As a (hopefully) final comment, this is the most recent output from the action:
> `failed to render template: template: ./.github/assets/pr-comments/success.md:7: function "date" not defined`

The latest version of the template:
https://github.com/Andre601/AdvancedServerList/blob/608c617b17b8e517f662bef350f4c229bab0856d/.github/assets/pr-comments/success.md

The placeholders aren't incomplete. It's just the markdown renderer messing stuff up because of the table.

Where the action is used:
https://github.com/Andre601/AdvancedServerList/blob/608c617b17b8e517f662bef350f4c229bab0856d/.github/workflows/pr-comment.yml#L77-L91

(Sorry for that much spam)

**Comment by chuhlomin** [comment]
> that timestamp actually has 23:04:05 as the GMT time

yeah, that example is in MST timezone (UTC -7), which is also layout option (`-0700`). I think I would need to add an option to pass a timezone to `date` function.

> I can't have hyphons in the var names?

I assume it's a Go limitation: variable name can only contain alpha-numeric characters and underscores

> function "date" not defined

GitHub actions pulls whatever image defined in `action.yml`. Try using `chuhlomin/render-template:funcs` action

**Comment by Andre601** [comment]
> GitHub actions pulls whatever image defined in `action.yml`. Try using `chuhlomin/render-template:funcs` action

Doesn't work. Now it doesn't find the repository at all...

**Comment by Andre601** [comment]
Updated to latest commit and now get this:
> `Error: failed to render template: template: ./.github/assets/pr-comments/success.md:7:33: executing "./.github/assets/pr-comments/success.md" at <"02 Jan 2006 23:04:05">: invalid value; expected string`

**Comment by chuhlomin** [comment]
I figured out what's was the issue: `gopkg.in/yaml.v3` parses string like `2023-08-06T15:08:28Z` directly into `time.Time` structure. Now supporting both `time.Time` and `string` in `date` func.
Also, added support for optional `timezone` input.

See example here: https://github.com/chuhlomin/ip/pull/3/files
Action run: https://github.com/chuhlomin/ip/actions/runs/4933077445/jobs/8816709010

```yaml
      - name: Render template
        uses: chuhlomin/render-template@funcs
        with:
          template: ./.github/assets/pr-comments/success.md
          result_path: rendered_template.md
          timezone: America/New_York
          vars: |
            link: https://github.com
            expire: 2023-08-06T15:08:28Z
```
\+ template
```
{{ .link | mdlink "Link" }}
{{ .expire | date "02 Jan 2006 15:04:05" }}
```

= result
```markdown
[Link](https://github.com/)
06 Aug 2023 11:08:28
```

**Comment by Andre601** [comment]
It *kinda* worked. It's just that the date is displayed as `<nil>`, so something in the parsing went wrong?
Probs the date template being wrong.
![grafik](https://github.com/chuhlomin/render-template/assets/11576465/0e5f09f3-d501-4be2-8a44-cb107e36e877)

**Comment by Andre601** [comment]
The issue was actually a wrong --jq setup I had, so it passed nothing to the placeholder resulting in the `<nil>`

![grafik](https://github.com/chuhlomin/render-template/assets/11576465/815d6e94-ea9c-4737-bceb-ddbf8b31c34c)

**Comment by Andre601** [comment]
Also, on an unrelated note: Me debugging stuff

![grafik](https://github.com/chuhlomin/render-template/assets/11576465/95a532da-89ee-4783-b4a7-ae8ee36764bb)

**Comment by chuhlomin** [comment]
> Me debugging stuff

yeah, debugging CI workflow always looks like it)

FYI, I made a [new release](https://github.com/chuhlomin/render-template/releases/tag/v1.7): 1.7 will all these changes.

**Comment by Andre601** [comment]
Alright. Will update the action.

Closing this as I already confirmed it working with the past commits.
